// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddFavorite'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function BuildSmartQueue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BuildSmartQueue'](arg1, arg2, arg3, arg4, arg5);
}

export function CheckAuthSession(arg1) {
  return window['go']['main']['App']['CheckAuthSession'](arg1);
}

export function FetchExternalAPI(arg1) {
  return window['go']['main']['App']['FetchExternalAPI'](arg1);
}

export function GetFavorites(arg1) {
  return window['go']['main']['App']['GetFavorites'](arg1);
}

export function GetFullStreamURL(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetFullStreamURL'](arg1, arg2, arg3, arg4);
}

export function GetHomeSettings(arg1) {
  return window['go']['main']['App']['GetHomeSettings'](arg1);
}

export function GetLyrics(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLyrics'](arg1, arg2, arg3);
}

export function GetPlaylist(arg1) {
  return window['go']['main']['App']['GetPlaylist'](arg1);
}

export function GetTrackPulseDuration(arg1, arg2) {
  return window['go']['main']['App']['GetTrackPulseDuration'](arg1, arg2);
}

export function GetUserProfile(arg1) {
  return window['go']['main']['App']['GetUserProfile'](arg1);
}

export function RemoveFavorite(arg1, arg2) {
  return window['go']['main']['App']['RemoveFavorite'](arg1, arg2);
}

export function SearchSongs(arg1) {
  return window['go']['main']['App']['SearchSongs'](arg1);
}

export function StartGoogleLogin() {
  return window['go']['main']['App']['StartGoogleLogin']();
}

export function UpdateHomeContent(arg1, arg2) {
  return window['go']['main']['App']['UpdateHomeContent'](arg1, arg2);
}
