// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuildSmartQueue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.SmartTrack>>;

export function GetFullStreamURL(arg1:string,arg2:string):Promise<string>;

export function GetLyrics(arg1:string,arg2:string,arg3:number):Promise<main.LyricsResult>;

export function GetPlaylist(arg1:string):Promise<Array<main.Song>>;

export function SearchSongs(arg1:string):Promise<Array<main.Song>>;
