// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildSmartQueue(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BuildSmartQueue'](arg1, arg2, arg3, arg4);
}

export function GetFullStreamURL(arg1, arg2) {
  return window['go']['main']['App']['GetFullStreamURL'](arg1, arg2);
}

export function GetLyrics(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLyrics'](arg1, arg2, arg3);
}

export function GetPlaylist(arg1) {
  return window['go']['main']['App']['GetPlaylist'](arg1);
}

export function SearchSongs(arg1) {
  return window['go']['main']['App']['SearchSongs'](arg1);
}
