// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFavorite(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function BuildSmartQueue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.SmartTrack>>;

export function CheckAuthSession(arg1:string):Promise<main.AuthUserInfo>;

export function GetFavorites(arg1:string):Promise<Array<main.FavoriteTrack>>;

export function GetFullStreamURL(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetHomeSettings(arg1:string):Promise<Array<main.HomeSettingRow>>;

export function GetLyrics(arg1:string,arg2:string,arg3:number):Promise<main.LyricsResult>;

export function GetPlaylist(arg1:string):Promise<Array<main.Song>>;

export function GetTrackPulseDuration(arg1:string,arg2:string):Promise<number>;

export function GetUserProfile(arg1:string):Promise<main.UserProfile>;

export function RemoveFavorite(arg1:string,arg2:string):Promise<void>;

export function SearchSongs(arg1:string):Promise<Array<main.Song>>;

export function StartGoogleLogin():Promise<void>;

export function UpdateHomeContent(arg1:string,arg2:main.HomeSettingRow):Promise<void>;
